manifest = "8175d561003036ba712ecf008e786c419c4e965f2b38ac3633af094285c908a1"

[[dependency]]
package = "github.com/buckaroo-pm/luadist-libjpeg"
target = "//:jpeg"

[[dependency]]
package = "github.com/buckaroo-pm/luadist-libpng"
target = "//:png"

[[dependency]]
package = "github.com/buckaroo-pm/luadist-libtiff"
target = "//:tiff"

[lock."github.com/buckaroo-pm/luadist-libjpeg"]
versions = [ "branch=master" ]
revision = "ca608f3c842d921fa369e798b114c42444f5791d"

[lock."github.com/buckaroo-pm/luadist-libpng"]
versions = [ "branch=master" ]
revision = "73a922fe950715414820b48fbf09810635302be5"

[lock."github.com/buckaroo-pm/luadist-libtiff"]
versions = [ "branch=master" ]
revision = "0bbc506dbcc9012cf726dcb338de8c1135858200"

[lock."github.com/buckaroo-pm/madler-zlib"]
versions = [ "branch=master" ]
revision = "81e58039a82d50f9c7768c651dce21834557aec1"
